apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:8OMapoZ2XQ==,iv:yHNSKjTno40duKD0RNmrMn4mP4pQKf9ojiJ9YonrD08=,tag:HjLbUfgUBRVbVXPys1E5NA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:d1s1DkvPixDxI7I=,iv:UVsf9RSgj4gPMBpvyw6fWj/HSeR6hFMotbg3JudUk1k=,tag:fnj87IWQly9Xh1jKfljuKA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:xJufN4zDvhapGXEH,iv:F03RbrtgeqmioUmV85PIn6kZ2SArC25Bj4/Oj1652l0=,tag:xHXMfIB+5RMwqT4gXfCW7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbUxkbDNNbk9MckU1Nzdi
            SFNSTTdjZ3FwczRTMG82ZS9NOVQyYmFQRmp3CjNjQ0YrUDRoNkhJR1hKczVZdjJq
            UEllOUxrbERpTHk5OEhpaXVoWlZHTHcKLS0tIGxIY1p0WE9BamhOT1c1RDlhakJz
            anNMaGpMM25mVEViWEpsZXZlOCtrbmMKdxhJ28oMsQhzQsUlybpzldGi8+Yi1gAA
            cQ8bEExPWO5tFuj3R7gAWdLgN1TKZqqRBmuXaILqRajfsigQNyNh+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T04:46:17Z"
    mac: ENC[AES256_GCM,data:kv99DczEbtk3C+lfuLJmxes95PMhctPZmYjCuKtiqwcvp49Mq0Z86DId0WOqmTKtbP/oN1qzkVapYZgnnxDwKG+KkocvwikCYqEoZK2bv7nL2NOvCshxQ9nS1V+LjmH7vnQp42UlQBVLLbM6b8Ljfsn3f/p7GXI3AmmJmOgeeyE=,iv:k8LHYj1QxPCKe/8UVsoBogmog/6ldbUnROhgHP578gQ=,tag:f+T6Px9/A5dahGDQlJW73w==,type:str]
    version: 3.13.3
